import json
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from src.models import get_db
from src.api.auth import get_current_user
from src.models.user import User
from src.models.plan import TrainingPlan, TrainingSession
from src.services.garmin_formatter import format_garmin_workout

router = APIRouter(prefix="/plans", tags=["sessions"])

MEDICAL_DISCLAIMER = (
    "AuraRun training recommendations are generated by AI to guide your fitness development. "
    "If you experience persistent chest pain, severe shortness of breath, sudden dizziness, "
    "or sharp localized muscle/joint pain, stop immediately and consult a medical professional."
)

def get_safety_alternative(session_type: str) -> dict:
    session_type_lower = session_type.lower()
    if session_type_lower in {"intervals", "tempo"}:
        return {
            "name": "Alternative Recovery Run",
            "description": "Replace the high-intensity sets with a slow, relaxed 25-30 minute jog in Zone 1-2, or swap to a Rest Day if you feel joint pain or deep fatigue.",
            "duration_minutes": 30,
            "distance_miles": 2.5
        }
    elif session_type_lower == "long run":
        return {
            "name": "Shortened Easy Run",
            "description": "Reduce total mileage by 50%. Run at a conversational pace. Focus on high cadence and smooth landing, or rest entirely if you feel joint stiffness.",
            "duration_minutes": 40,
            "distance_miles": 3.5
        }
    else:
        return {
            "name": "Complete Rest Day",
            "description": "Take a full day off to let muscle tissue and joints recover. You can execute 15 minutes of light stretching or yoga if helpful.",
            "duration_minutes": 0,
            "distance_miles": 0.0
        }

@router.get("/sessions/{session_id}")
def get_session_detail(
    session_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    session = db.query(TrainingSession).filter(TrainingSession.id == session_id).first()
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
        
    # Verify ownership
    plan = db.query(TrainingPlan).filter(
        TrainingPlan.id == session.plan_id,
        TrainingPlan.user_id == current_user.id
    ).first()
    if not plan:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You do not have access to this training plan"
        )
        
    # Parse JSON structures safely
    def safe_parse_json(val):
        if not val:
            return []
        try:
            return json.loads(val)
        except Exception:
            return []
            
    warm_up = safe_parse_json(session.warm_up_json)
    main_set = safe_parse_json(session.main_set_json)
    cool_down = safe_parse_json(session.cool_down_json)
    
    # Dynamic fallback parser if database arrays are empty
    if not warm_up and not main_set and not cool_down and session.garmin_instructions_text:
        import re
        lines = session.garmin_instructions_text.split("\n")
        for line in lines:
            line_strip = line.strip()
            if not line_strip:
                continue
            # Remove leading number like "1. ", "2) ", or "- "
            content = re.sub(r'^\d+[\.\)\-]\s*', '', line_strip).strip()
            if not content:
                continue
            
            content_lower = content.lower()
            if "warm up" in content_lower or "warm-up" in content_lower:
                warm_up.append(content)
            elif "cool down" in content_lower or "cool-down" in content_lower or "cooldown" in content_lower:
                cool_down.append(content)
            else:
                main_set.append(content)
    
    alternative = get_safety_alternative(session.type)
    
    return {
        "id": session.id,
        "date": session.date.isoformat(),
        "type": session.type,
        "name": session.name,
        "description": session.description,
        "duration_minutes": session.duration_minutes,
        "distance_miles": session.distance_miles,
        "warm_up": warm_up,
        "main_set": main_set,
        "cool_down": cool_down,
        "target_pace_range": session.target_pace_range or "N/A",
        "target_hr_zone": session.target_hr_zone or "N/A",
        "target_rpe": session.target_rpe or 5,
        "garmin_instructions_text": session.garmin_instructions_text or format_garmin_workout(
            session.name, warm_up, main_set, cool_down,
            session.target_pace_range or "N/A", session.target_hr_zone or "N/A", session.target_rpe or 5
        ),
        "status": session.status,
        "safety_alternative": alternative,
        "medical_disclaimer": MEDICAL_DISCLAIMER
    }
